#!/usr/bin/env bash
VERSION="${FLOW_VERSION:-10}"
SAMPLING="${FLOW_SAMPLING:-1}"
COLLECTOR_HOST="${FLOW_COLLECTOR_HOST:-127.0.0.1}"
COLLECTOR_PORT="${FLOW_COLLECTOR_PORT:-9999}"
INTERFACES="${FLOW_INTERFACES:-eth0}"

exec 2>&1
IFS=',' read -r -a INTERFACES <<< "${INTERFACES}"
echo "Evaluate network interfaces:"
for int in "${INTERFACES[@]}"; do
    exec softflowd -A nano -d -i ${int} -v ${VERSION} -s ${SAMPLING} -n ${COLLECTOR_HOST}:${COLLECTOR_PORT}
done
